; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://platformio.org

[env:esp32-s3-devkitc-1-psram]
board_build.arduino.memory_type = dio_qspi  ; Stable memory layout for 2MB PSRAM
extends                 = env:esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
board = ESP-General
board_build.partitions = custom_4Mb_full.csv
build_src_filter = ${env.build_src_filter} +<../boards/ESP-General>
build_flags =
	${env.build_flags}
	-Iboards/ESP-General
	-DUSB_as_HID=1
	; grove pins disabled to clear space
	-DGROVE_SDA=-1
	-DGROVE_SCL=-1
	-DTXLED=-1
	-DLED_ON=HIGH
	-DLED_OFF=LOW
	; sd card pins disabled
	-DSDCARD_CS=-1
	-DSDCARD_SCK=-1
	-DSDCARD_MISO=-1
	-DSDCARD_MOSI=-1
	; === ST7789V Display & Driver Config ===
	-DST7789_DRIVER=1              ; Force ST7789 display controller selection
	-DUSE_LGFX_LIBRARY=1           ; Resolves 'tft_logger' writecommand errors 
	-DTFT_WIDTH=240
	-DTFT_HEIGHT=320
	-DTFT_INVERSION_ON=1           ; Corrects colors for standard ST7789 displays
	-DSPI_FREQUENCY=27000000       ; Limits SPI speed to stable 27MHz for shared bus
	-DROTATION=1
	-DBACKLIGHT=-1
	-DMINBRIGHT=160
	-DSMOOTH_FONT=1
	-DTFT_DISPON=0x29
	-DTFT_DISPOFF=0x28
	-DTFT_CS=10
	-DTFT_DC=7
	-DTFT_RST=6
	-DTFT_MOSI=11
	-DTFT_SCLK=12
	-DTOUCH_CS=-1
	-DTFT_BL=-1
	; text sizes
	-DFP=1
	-DFM=2
	-DFG=3
	; === 5-Way Digital Navigation Buttons ===
	-DSEL_BTN=9
	-DUP_BTN=1
	-DDW_BTN=2
	-DLFT_BTN=3
	-DRGHT_BTN=8
	-DBTN_ALIAS='"OK"'
	-DBUTTONS_ACTIVE_LEVEL=LOW     ; Internal Pull-up activation
	; === Disable CC1101 ===
	-DCC1101_GDO0_PIN=-1
	-DCC1101_SS_PIN=-1
	-DCC1101_MOSI_PIN=-1
	-DCC1101_SCK_PIN=-1
	-DCC1101_MISO_PIN=-1
	; === NRF24L01+ Config (Shared SPI with Display) ===
	-DUSE_NRF24_VIA_SPI=1
	-DNRF24_CE_PIN=4
	-DNRF24_SS_PIN=5
	-DNRF24_MOSI_PIN=11
	-DNRF24_SCK_PIN=12
	-DNRF24_MISO_PIN=13
	; === Global Hardware SPI Fallback ===
	-DSPI_SCK_PIN=12
	-DSPI_MOSI_PIN=11
	-DSPI_MISO_PIN=13
	-DSPI_SS_PIN=10
	-DDEVICE_NAME='"Bruce Shared S3 Mini"'
lib_deps =
	${env.lib_deps}
